name: Code Tests

on: ["push", "pull_request"]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        env:
          BOMGAR_USERNAME: ${{ secrets.BOMGAR_USERNAME }}
          BOMGAR_PASSWORD: ${{ secrets.BOMGAR_PASSWORD }}
          SCHEDULESOURCE_TOKEN: ${{ secrets.SCHEDULESOURCE_TOKEN }}
          SERVICENOW_USERNAME: ${{ secrets.SERVICENOW_USERNAME }}
          SERVICENOW_PASSWORD: ${{ secrets.SERVICENOW_PASSWORD }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          python -m pytest --cov-config=.coveragerc -q ./tests/integration_tests.py --cov=src --cov=src/integrations --cov=src/ui
          coveralls
